package com.corevalue.constants.menu;

public interface FileMenuConst extends MenuConst {
    String SUBMENU_SEARCH_CASE_FILES_ID = SUBMENU_BASE_PREFIX + "i11";
    String SUBMENU_NEW_CASE_FILE_ID = SUBMENU_BASE_PREFIX + "i12";
    String SUBMENU_NEW_CASE_FILE_FROM_REFERRAL_ID = SUBMENU_BASE_PREFIX + "i12CT";
    String SUBMENU_CASE_FILE_SUMMARY_ID = SUBMENU_BASE_PREFIX + "i15";
    String SUBMENU_SEARCH_FOR_ACTION_ID = SUBMENU_BASE_PREFIX + "i13";
    String SUBMENU_SEARCH_FOR_ACTION_BY_CONTACT_ID = SUBMENU_BASE_PREFIX + "i131";
    String SUBMENU_NEW_ACTION_ID = SUBMENU_BASE_PREFIX + "i14";
    String SUBMENU_NEW_ACTION_FROM_REFERRAL_ID = SUBMENU_BASE_PREFIX + "i14CT";
    String SUBMENU_CHANGE_ACTION_TEMPLATE_ID = SUBMENU_BASE_PREFIX + "i16C"; // changed ID om main.jsp, because it duplicate logout
    String SUBMENU_CALENDAR_ID = SUBMENU_BASE_PREFIX + "i17i";
    String SUBMENU_CONFLICTS_CHECKING_ID = SUBMENU_BASE_PREFIX + "i18";
    String SUBMENU_CALCULATE_DATE_ID = SUBMENU_BASE_PREFIX + "i17";
    String SUBMENU_SEND_MAIL_ID = SUBMENU_BASE_PREFIX + "i160";
    String SUBMENU_LOGOUT_ID = SUBMENU_BASE_PREFIX + "i16";
}
